# Generated by Django 5.2.5 on 2025-09-21 09:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_summarizationsession_summarizationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document'),
        ),
    ]
