# Generated by Django 5.2.5 on 2025-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='purpose',
            field=models.CharField(default='signup', max_length=20),
        ),
    ]
